version: '2'
services:
  hub:
    image: selenium/hub:3.1.0
    ports:
      - "4444"
    environment:
      - GRID_BROWSER_TIMEOUT=30
  chrome:
    image: selenium/node-chrome-debug:3.1.0
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - no_proxy=localhost
      - HUB_ENV_no_proxy=localhost
    ports:
      - "5900:5900"
  mustadio:
    image: yetanotherlucas/mustadio
    ports:
      - "3000"
  the-internet:
    image: gprestes/the-internet
    ports:
      - "5000"
  gridium:
    build: .
    environment:
      - S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
      - S3_DEFAULT_REGION=$S3_DEFAULT_REGION
      - S3_ROOT_BUCKET=$S3_ROOT_BUCKET
      - GRIDIUM_TR_PID=$GRIDIUM_TR_PID
      - GRIDIUM_TR_PW=$GRIDIUM_TR_PW
      - GRIDIUM_TR_URL=$GRIDIUM_TR_URL
      - GRIDIUM_TR_USER=$GRIDIUM_TR_USER
      - BUILD_NUMBER=$BUILD_NUMBER
    command: "tail -f /dev/null"
